# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_rscarbon_wrappers", use_symbols = TRUE, package_name = "rscarbon")

#' @usage NULL
#' @useDynLib rscarbon, .registration = TRUE
NULL

rust_calibrate <- function(age, error, start, end, precision, path_to_calibration) .Call(wrap__rust_calibrate, age, error, start, end, precision, path_to_calibration)


# nolint end
