# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_rscarbon_wrappers", use_symbols = TRUE, package_name = "rscarbon")

#' @usage NULL
#' @useDynLib rscarbon, .registration = TRUE
NULL

rust_calibrate <- function(age, error, start, end, precision, calbs) .Call(wrap__rust_calibrate, age, error, start, end, precision, calbs)

Calibration <- new.env(parent = emptyenv())

Calibration$read_14c <- function(path_to_calibration) .Call(wrap__Calibration__read_14c, path_to_calibration)

#' @export
`$.Calibration` <- function (self, name) { func <- Calibration[[name]]; environment(func) <- environment(); func }

#' @export
`[[.Calibration` <- `$.Calibration`


# nolint end
